spring.application.name=intibak-control

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

erciyesUrl=https://dbp.erciyes.edu.tr/Program/P3.aspx?Fak=103&lang=0&Pro=103051


#Ollama base url
spring.ai.ollama.base-url=http://localhost:11434


#LLM Configuration

spring.ai.ollama.chat.options.model=llama3.2


#Embedding Configuration

spring.ai.ollama.embedding.options.model=nomic-embed-text

